#!/usr/bin/env python3
"""Generate runtime/syscall_names.h from the runtime's numeric syscall dispatcher.

The PS2 runtime's syscall dispatch is a switch in
    tools/PS2Recomp/ps2xRuntime/src/lib/Kernel/Syscalls/Dispatcher.cpp
that maps a numeric syscall id ($v1) to a C++ handler. VULCAN 4's harness needs to *name*
the syscalls GT4 issues so it can produce a no-BIOS backlog, and we do not want a second,
hand-maintained copy of that table living in the runtime where it could silently drift.

So we transcribe the dispatcher's own switch into a generated header. Regenerate with:

    python3 tools/harness/gen_syscall_names.py

after changing the dispatcher. The generated header is NOT committed to the repository --
it is written into the upstream tree, which is gitignored, and is rebuilt as part of the
harness build (see docs/FIRST-BOOT.md).
"""

from __future__ import annotations

import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
DISPATCHER = REPO / "tools/PS2Recomp/ps2xRuntime/src/lib/Kernel/Syscalls/Dispatcher.cpp"
OUTPUT = REPO / "tools/PS2Recomp/ps2xRuntime/include/runtime/syscall_names.h"

# Anything matching this is not a handler call.
NOT_HANDLERS = {"TODO", "dispatchNumericSyscall", "dispatchSyscall", "return", "std"}

# case <number>:  [optional comment lines]  Handler(args...)
CASE_RE = re.compile(
    r"case\s+(0x[0-9A-Fa-f]+|\d+)\s*:\s*(?://[^\n]*\s*)*([A-Za-z_][A-Za-z_0-9]*)\s*\("
)


def main() -> int:
    if not DISPATCHER.is_file():
        print(f"STUCK: dispatcher not found at {DISPATCHER}", file=sys.stderr)
        return 1

    source = DISPATCHER.read_text(encoding="utf-8", errors="replace")

    names: dict[int, str] = {}
    for match in CASE_RE.finditer(source):
        number = int(match.group(1), 0)
        handler = match.group(2)
        if handler in NOT_HANDLERS:
            continue
        # A numeric id can appear more than once (shared handler); first one wins.
        names.setdefault(number, handler)

    if not names:
        print("STUCK: no syscall handlers parsed -- the dispatcher shape changed", file=sys.stderr)
        return 1

    lines = [
        "// syscall_names.h - GENERATED by tools/harness/gen_syscall_names.py from",
        "//   tools/PS2Recomp/ps2xRuntime/src/lib/Kernel/Syscalls/Dispatcher.cpp",
        "//",
        "// Do not edit by hand. Regenerate if the dispatcher changes.",
        "#pragma once",
        "#include <cstdint>",
        "",
        "struct SyscallName { uint32_t id; const char *name; };",
        "",
        "static const SyscallName kSyscallNames[] = {",
    ]
    for number in sorted(names):
        lines.append(f'    {{ 0x{number:02X}, "{names[number]}" }},')
    lines.append("};")
    lines.append("")
    lines.append(f"static const unsigned kSyscallNameCount = {len(names)};")
    lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT} with {len(names)} syscall names")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
